# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_product_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _template: SyliusWebBundle:Backend/Product:index.html.twig
        _sortable: true
        _sorting:
            name: desc
    requirements:
        _method: GET

sylius_backend_product_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _template: SyliusWebBundle:Backend/Product:create.html.twig
        _redirect: sylius_backend_product_show

sylius_backend_product_update:
    pattern: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.product:updateAction
        _template: SyliusWebBundle:Backend/Product:update.html.twig
        _redirect: sylius_backend_product_show

sylius_backend_product_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.product:deleteAction
        _redirect: sylius_backend_product_index

sylius_backend_product_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:showAction
        _template: SyliusWebBundle:Backend/Product:show.html.twig
