# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_promotion_coupon_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.promotion_coupon:deleteAction
        _redirect: referer
