# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_backend_province_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_addressing.controller.province:deleteAction
        _redirect: referer
